### ISSUE TITLE
Suggestion: Let beta_diversity use a pandas DataFrame index as ids by default

### ISSUE THREAD

**Issue by Midnighter** [scikit-bio/scikit-bio#1808]
Just a small suggestion: Instead of

```py
beta_diversity("method", df, ids=df.index)
```

use the index as `ids` by default.

**Comment by wasade** [comment]
This is a wonderful idea. Would you be interested in submitting a PR to accommodate this use?

**Comment by Midnighter** [comment]
I'll see if I can fit it in. Work's pretty hectic at the moment, though.
