### ISSUE TITLE
Support for scipy > 1.10.1

### ISSUE THREAD

**Issue by tjni** [scikit-bio/scikit-bio#1875]
I saw from the list of changes in 0.5.9 that https://github.com/biocore/scikit-bio/pull/1867 caps the scipy version at 1.10.1. In [nixpkgs](https://github.com/NixOS/nixpkgs), we carry only one version (usually the latest) of each Python package, and our scipy version is already at 1.11.2. I'm doing some information gathering to decide what we should do:

1. What is the incompatibility with later versions of scipy, and what sort of degradation in functionality exists?
2. Does this affect 0.5.8 as well?

Thank you for any insight into this!

**Comment by antgonza** [comment]
If I remember correctly it was something with the `kulsinski` tests failing; you can [check the build before the cap](https://github.com/biocore/scikit-bio/actions/runs/5716591822/job/15488467505). 

Anyway, looking online the solution might be as simple as replacing kulsinski for kulsinski1 but not sure:
https://docs.scipy.org/doc/scipy-1.10.0/reference/generated/scipy.spatial.distance.kulsinski.html

Thoughts?

**Comment by qiyunzhu** [comment]
@antgonza I think we should address this issue. `kulsinski` as a beta diversity metric is only mentioned in an [internal list](https://github.com/scikit-bio/scikit-bio/blob/8c4825757c780ead5a41af8997b699021af0322b/skbio/diversity/_driver.py#L288) that is not exposed to the user. I performed literature search and couldn't find any paper that uses `kulsinski` or `kulczynski1` as a beta diversity metric. As [this comment](https://github.com/scikit-learn/scikit-learn/pull/25212#pullrequestreview-1223050186) pointed out, `kulczynski1` returns `inf` for a vector against itself. In my test, `kulsinski` also returns a positive value for a vector against itself. For example, `kulsinski(np.array([1,0,1,0,1]), np.array([1,0,1,0,1]))` is 0.4. Therefore, I think either metric is not a suitable beta diversity metric, and we should simply remove it from skbio.

**Comment by antgonza** [comment]
After a quick search I found these papers that cite this metric (used google vs. pubmed):
1. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8778696/
2. https://www.frontiersin.org/articles/10.3389/fbioe.2020.556413/full
3. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8418097/pdf/main.pdf
4. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2948603/#SD1

However, I agree that fixing or removing so we can remove the cap is a good idea.

**Comment by qiyunzhu** [comment]
@antgonza Thanks for the findings and opinion!

I checked the four literatures you found. I think that they may not be ideal cases supporting using Kulsinski as a beta diversity metric. Specifically, 1) used Kulsinski as an alpha diversity metric. 2) used it to assess genomic distance (along with metrics like L1/L2 and Hamming). 3) used it to evaluate clustering of disease groups (not microbial communities). 4) the first author's name is "Kulsinski" but the paper didn't use this metric.

**Comment by antgonza** [comment]
Then sounds like it's fine to remove.

Note that the 4th the metric is used as part of the original comparison (and it might be one of the reason it was included in the original Qiime); if you check [the supplemental](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2948603/bin/NIHMS226887-supplement-1.pdf) you would see the results there.

**Comment by qiyunzhu** [comment]
@antgonza I did note that `kulsinski` is mentioned somewhere (a few places) in the current QIIME 2 documentation. Therefore to safely remove it we need to coordinate with @ebolyen .

**Comment by jowodo** [comment]
According to https://github.com/scipy/scipy/issues/19274#issuecomment-1731862215 at least **scipy** 1.11.2 is needed for python 3.12. As long as **scipy<1.10.1** is capped, **scikit-bio** is not able to run with python3.12.

**Comment by qiyunzhu** [comment]
@jowodo @antgonza Thanks for the comment! We have added support for SciPy 1.11+ in #1887 .

The next challenge is to add Python 3.12 support. Although scikit-bio runs on Python 3.12, some unit tests fail due to gzip file content discrepancy. This needs to be addressed as high priority.
