### ISSUE TITLE
trouble installing skbio from conda

### ISSUE THREAD

**Issue by Storyboardslee** [scikit-bio/scikit-bio#1878]
Hi skbio team, 
I was trying to install skbio using conda, and I have tried all possible commands listed [here](https://anaconda.org/conda-forge/scikit-bio). The error message is the following:

PackagesNotFoundError: The following packages are not available from current channels:

  - scikit-bio

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/gurobi/osx-arm64
  - https://conda.anaconda.org/gurobi/noarch
  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/r/osx-arm64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

Any chance you can help me identify the issue? What additional channel should I add to be able to install skbio?

Best, Cindy

**Comment by Storyboardslee** [comment]
I figured out that this is due to the fact that my machine is ARM. Creating a different conda env for osx-64 solved the issue. I  am closing this issue now.

**Comment by qiyunzhu** [comment]
Closing it since it is resolved.
