### ISSUE TITLE
scikit-bio.org is gone.

### ISSUE THREAD

**Issue by xguse** [scikit-bio/scikit-bio#1882]
So I am not gonna lie, I am more than a little concerned about this.

Is this project gonna be around much longer? All your docs and your home page are:
<img width="1027" alt="image" src="https://github.com/scikit-bio/scikit-bio/assets/138931/22f351c7-d9d5-4c24-a40c-65814000abc7">

Are you guys ok?

**Comment by mortonjt** [comment]
scikit-bio has been moved to https://scikit.bio/

Major upgrades incoming!

**Comment by xguse** [comment]
> scikit-bio has been moved to https://scikit.bio/
> 
> Major upgrades incoming!

Super excited about that.

But does https://scikit.bio/ work for you? Because this is what I am getting
![image](https://github.com/scikit-bio/scikit-bio/assets/138931/e5d35562-2124-4600-88d6-3f15b8d61f7f)

**Comment by qiyunzhu** [comment]
Hello @xguse , Thanks for noting this issue. As @mortonjt  mentioned, the website has been moved to scikit.bio. Per your reminder, we set up domain forwarding from scikit-bio.org to the new website. We apologize for not announcing this change more timely, as we understand that this may have caused inconvenience and confusion. Our team take the stability and reliability of the scikit-bio seriously. We are committed to ensuring that it is consistently available and dependable.

**Comment by qiyunzhu** [comment]
@xguse Can you check if scikit.bio works for you now? Thanks!

**Comment by xguse** [comment]
@qiyunzhu I am afraid not

**Comment by xguse** [comment]
> @xguse Can you check if scikit.bio works for you now? Thanks!

Ok I am not sure why this would be an issue, but it seems that I can reach it through my phone, but not my work computer. Can you think of why it might not work from a work network?

**Comment by xguse** [comment]
Ok guys. I am sorry for the confusion. It seems that my work's network rules are blocking this bc it is a "newly registered domain".

However, i was only informed of this on the http (non encrypted) route?
<img width="1096" alt="image" src="https://github.com/scikit-bio/scikit-bio/assets/138931/c52e3d3d-f204-4c54-9fda-34540a4ae351">

So it looks like my company is being a bit over-zealous in its nannying at the moment.

**Comment by qiyunzhu** [comment]
@xguse Hmmm... It could be because "scikit.bio" was indeed just registered <48 hr ago. I hope that it won't be a problem in a few days. The scikit-bio website now has HTTPS enforced.

**Comment by xguse** [comment]
yep. Thanks for your swift help!

Now if you guys would let me inherit from `DNA` without having to completely re-implement its entire logic starting from `GrammeredSeq` before I am able to add one simple new method I would be golden!

jk...   sort of

**Comment by qiyunzhu** [comment]
@xguse thanks for the suggestion. If you could please elaborate it in a new issue, we will be happy to discuss it and assess the potential to add this functionality.

**Comment by xguse** [comment]
> If you could please elaborate it in a new issue, we will be happy to discuss it and assess the potential to add this functionality.

@qiyunzhu someone (@clintval) already has. Its here: https://github.com/scikit-bio/scikit-bio/issues/1637

I agree with everything he says including the 2 options he proposes. I will copy this again over there.
