### ISSUE TITLE
Scikit-bio installation with Python 3.12 causes failures when testing

### ISSUE THREAD

**Issue by Bharath-Sathappan** [scikit-bio/scikit-bio#1897]
I followed these [instructions](https://github.com/scikit-bio/scikit-bio/blob/master/.github/CONTRIBUTING.md#setting-up-a-development-environment) to install scikit-bio with Python version 3.12.

At the `make test` step, I encountered the below failures:
```
FAIL: test_open_gzip (__main__.TestWriteBufferedReader.test_open_gzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 343, in test_open_gzip
    self.compare_gzip_file_contents(self.get_contents(self.gzip_file),
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'le_file\x00' != b'\x8a\x9d\xf4\x165\x00\x00\x00'
======================================================================
FAIL: test_open_gzip_encoding (__main__.TestWriteBufferedReader.test_open_gzip_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 365, in test_open_gzip_encoding
    self.compare_gzip_file_contents(
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'g5_file\x00' != b'&\x05\xd3\xe1\x05\x00\x00\x00'
======================================================================
FAIL: test_open_gzip (__main__.TestWriteBytesIO.test_open_gzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 493, in test_open_gzip
    self.compare_gzip_file_contents(self.get_contents(self.gzip_file),
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'' != b'\x8a\x9d\xf4\x165\x00\x00\x00'
======================================================================
FAIL: test_open_gzip_encoding (__main__.TestWriteBytesIO.test_open_gzip_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 501, in test_open_gzip_encoding
    self.compare_gzip_file_contents(
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'' != b'&\x05\xd3\xe1\x05\x00\x00\x00'
======================================================================
FAIL: test_open_gzip (__main__.TestWriteNamedTemporaryFile.test_open_gzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 343, in test_open_gzip
    self.compare_gzip_file_contents(self.get_contents(self.gzip_file),
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'py4ezep\x00' != b'\x8a\x9d\xf4\x165\x00\x00\x00'
======================================================================
FAIL: test_open_gzip_encoding (__main__.TestWriteNamedTemporaryFile.test_open_gzip_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 365, in test_open_gzip_encoding
    self.compare_gzip_file_contents(
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'v7olg_j\x00' != b'&\x05\xd3\xe1\x05\x00\x00\x00'
======================================================================
FAIL: test_open_gzip (__main__.TestWriteTemporaryFile.test_open_gzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 343, in test_open_gzip
    self.compare_gzip_file_contents(self.get_contents(self.gzip_file),
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'\x08\x004\xb6Se\x02\xff' != b'\x8a\x9d\xf4\x165\x00\x00\x00'
======================================================================
FAIL: test_open_gzip_encoding (__main__.TestWriteTemporaryFile.test_open_gzip_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 365, in test_open_gzip_encoding
    self.compare_gzip_file_contents(
  File "/home/bsathappan/scikit-bio/skbio/io/tests/test_util.py", line 329, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'\x08\x004\xb6Se\x02\xff' != b'&\x05\xd3\xe1\x05\x00\x00\x00'
----------------------------------------------------------------------
Ran 220 tests in 2.498s
FAILED (failures=8)
```

I repeated the installation process with Python version 3.11, and everything worked properly and all tests passed.

**Comment by qiyunzhu** [comment]
@Bharath-Sathappan Thank you for reporting this! We also noticed it. According to the error message, it seems to be related to changes in Python 3.12's gzip library. We will need to work on it (as a priority). For now, I would suggest that you set up the development environment with `python==3.11`.

**Comment by qiyunzhu** [comment]
After some tests I think I have approached the problem, although not yet able to resolve it. I think that it is related to that Python 3.12's gzip module writes data into a buffer before compressing (see [details](https://github.com/python/cpython/pull/101251). Some issues were raised and fixed (see [details](https://github.com/python/cpython/issues/105808)), but it still seems not working properly in skbio.

Without being able to fix the unit tests, all I can potentially do is to temporarily disable these tests to unblock the adoption of Python 3.12. This is not ideal, apparently, nor am I sure if this issue won't break skbio's functionality. Because skbio contains a quite sophisticated I/O system which I am not familiar with, I would like to seek help from @wasade @antgonza @ebolyen who may be more familiar with it. Will appreciate your input!

***

Basically, the problem is in this helper function: [`check_open_state_contents`](https://github.com/scikit-bio/scikit-bio/blob/bb4e5e4ff2f2a66057dcc208186a6bec239661d3/skbio/io/tests/test_util.py#L306). It does `result.write(contents)`. However, in Python 3.12, what it writes will not be immediately flushed to the target gzip (file or whatever). skbio seems to be able to read and write simultaneously in a gzip file, which is cool functionality, but this issue breaks it.

I have tested `result.flush()`, `result.buffer.flush()` and `file.flush()`. None of them worked.

The only thing that worked in my test is too add a line `result.close()` after the `write` line. This effectively flushes the content to the gzip file. This patch solved the problem in [`TestWriteBufferedReader`](https://github.com/scikit-bio/scikit-bio/blob/bb4e5e4ff2f2a66057dcc208186a6bec239661d3/skbio/io/tests/test_util.py#L513). However, it won't work with the remaining unit tests such as [`TestWriteNamedTemporaryFile`](https://github.com/scikit-bio/scikit-bio/blob/bb4e5e4ff2f2a66057dcc208186a6bec239661d3/skbio/io/tests/test_util.py#L538C7-L538C34), which requires the file object to remain open.

**Comment by actapia** [comment]
It looks like many of the tests in `test_util.py`, including those that are failing here, depend on the `__del__` function of various file-like objects created in `check_open_state_contents` being called immediately after `check_open_state_contents` returns. When `__del__` is called, the objects flush, and, in some cases, close.

I know Python doesn't guarantee precisely when `__del__` will be called for an object, but it seems that CPython reliably deletes objects that have no referrers after a function returns. Unfortunately, in Python 3.12, it looks like GzipFile's new buffer creates a cyclic reference, and this seems to stop `__del__` from being called on all the necessary objects. (For the failing tests, in `check_open_state_contents`, we have `result.buffer.raw._buffer.raw.gzip_file == result.buffer.raw`.) 

If we delete `result` and manually tell Python to perform garbage collection, the tests pass again.

```diff
diff --git a/skbio/io/tests/test_util.py b/skbio/io/tests/test_util.py
index 21434a0a..fd979fbd 100644
--- a/skbio/io/tests/test_util.py
+++ b/skbio/io/tests/test_util.py
@@ -11,6 +11,7 @@ import tempfile
 import shutil
 import io
 import os.path
+import gc

 try:
     import httpretty
@@ -321,6 +322,10 @@ class WritableBinarySourceTests:
             self.assertTrue(result.closed)
             self.check_closed(file, True)

+        gc.collect()
+        del result
+        gc.collect()
+
     def compare_gzip_file_contents(self, a, b):
         # The first 10 bytes of a gzip header include a timestamp. The header
         # can be followed by other "volatile" metadata, so only compare gzip
```

Actually, I'm not entirely sure why the first `gc.collect()` seems to be needed.

Anyway, I think a better way of addressing this problem might be to use an unbuffered version of `GzipFile` based on the version from CPython 3.11. The tests seem to pass on Python 3.12 with the changes at https://github.com/actapia/scikit-bio/tree/util_py312 .

**Comment by qiyunzhu** [comment]
@actapia Thank you very much for finding a working solution!! Would you like to submit a pull request to scikit-bio? Alternatively, we can attempt to implement the solution you suggested. What do you think? (I am pinging our engineer @mataton so he will keep track of this.)

**Comment by actapia** [comment]
> @actapia Thank you very much for finding a working solution!! Would you like to submit a pull request to scikit-bio? Alternatively, we can attempt to implement the solution you suggested. What do you think? (I am pinging our engineer @mataton so he will keep track of this.)

Thank you. I've submitted a pull request, #1928, that incorporates the unbuffered version of `GzipFile`.

**Comment by mataton** [comment]
@actapia @qiyunzhu Just out of curiosity, I decided to see what would happen if we remove the first `gc.collect` and I found the following unittests still fail, FYI.

![Screenshot 2024-02-05 at 9 45 34 AM](https://github.com/scikit-bio/scikit-bio/assets/62309966/5d9e59ed-2560-4693-8a92-222e6afc0dae)

**Comment by qiyunzhu** [comment]
@actapia We took the `gc` solution you suggested (#1930). It should unblock Python 3.12 now. There is no use case that might break as far as we know. But we will further test to make sure before the next release.
