### ISSUE TITLE
Refactoring the lifecycle decorators

### ISSUE THREAD

**Issue by qiyunzhu** [scikit-bio/scikit-bio#1916]
Currently most scikit-bio functions and methods have a decorator on top of it to indicate the life cycle status. For example: `@experimental(as_of='0.5.10')`. However, as @wasade [pointed out](https://github.com/scikit-bio/scikit-bio/pull/1913#discussion_r1450872771), this information has not been used in any case. Also, the information is usually outdated.

> What other packages are doing something like this? My concern is that while this did get setup, I don't recall seeing any PRs over the history of the project which actually changed things associated with these decorators nor am I aware of consumers of the library using this information (though I may be wrong there?)

Perhaps we can follow the suit of other packages by removing this decorators and only note the life cycle information in the documentation. Here are the examples from [Pandas](https://github.com/pandas-dev/pandas/blob/a671b5a8bf5dd13fb19f0e88edc679bc9e15c673/pandas/io/parsers/readers.py#L171) and [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/3f89022fa/sklearn/decomposition/_pca.py#L199).

@mortonjt and @mataton , what do you think?

**Comment by mortonjt** [comment]
I’m OK with ditching it

**Comment by mataton** [comment]
@qiyunzhu Getting rid of it makes sense to me.
