### ISSUE TITLE
CLR error for vector of size 1

### ISSUE THREAD

**Issue by michaelsilverstein** [scikit-bio/scikit-bio#1918]
This is a trivial and low-priority case, but the current `clr` function raises an error when a vector of size 1 is passed to it.
For example, 
```python
x = [1]
clr(x)
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
Cell In[81], line 1
----> 1 clr(x)

File /projectnb/talbot-lab-data/msilver/.conda/envs/msilver/lib/python3.8/site-packages/skbio/stats/composition.py:465, in clr(mat)
    463 mat = closure(mat)
    464 lmat = np.log(mat)
--> 465 gm = lmat.mean(axis=-1, keepdims=True)
    466 return (lmat - gm).squeeze()

File /projectnb/talbot-lab-data/msilver/.conda/envs/msilver/lib/python3.8/site-packages/numpy/core/_methods.py:167, in _mean(a, axis, dtype, out, keepdims, where)
    163 arr = asanyarray(a)
    165 is_float16_result = False
--> 167 rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
    168 if rcount == 0 if where is True else umr_any(rcount == 0, axis=None):
    169     warnings.warn("Mean of empty slice.", RuntimeWarning, stacklevel=2)

File /projectnb/talbot-lab-data/msilver/.conda/envs/msilver/lib/python3.8/site-packages/numpy/core/_methods.py:76, in _count_reduce_items(arr, axis, keepdims, where)
     74     items = nt.intp(1)
     75     for ax in axis:
---> 76         items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
     77 else:
     78     # TODO: Optimize case when `where` is broadcast along a non-reduction
     79     # axis and full sum is more excessive than needed.
     80 
     81     # guarded to protect circular imports
     82     from numpy.lib.stride_tricks import broadcast_to

AxisError: axis -1 is out of bounds for array of dimension 0
```
As far as I can tell, this error arises from applying `closure()` before computing the clr (https://github.com/scikit-bio/scikit-bio/blob/91e1643b95e06d4afaacf69a94eb3690789955fa/skbio/stats/composition.py#L460C23-L460C23), which reduces this vector of size 1 to a scalar, which causes the error. Without `closure()`, the function works as intended:
```python
x = [1]
lmat = np.log(x)
gm = lmat.mean(axis=-1, keepdims=True)
lmat - gm 
------------
array([0.])
```
Maybe `closure()` shouldn't squeeze vectors of size 1 to scalars?

**Comment by mortonjt** [comment]
Hi, thanks for raising this issue. I don't think this is a real error, since compositions with 1 dimension don't make sense (i.e. pick any scalar, and if you compute CLR, it is always going to be zero).

We can raise a `ValueError` highlighting that 1 dimensional scalars are not an acceptable input.

**Comment by michaelsilverstein** [comment]
Hello, thanks for the quick response. That makes sense. 

My current use case, computing the Aitchison distance between all sample pairs in a dataset, would benefit from returning 0 for (admittedly bad) samples that only share the same single taxon, but this is a pretty uncommon issue and easy enough to work around.
