### ISSUE TITLE
Broken link in `diversity.alpha.simpson_e` docstring

### ISSUE THREAD

**Issue by colinvwood** [scikit-bio/scikit-bio#1923]
The first reference link (below) times out when followed.

https://github.com/scikit-bio/scikit-bio/blob/27085788e5acf4a67cc5fa0d157fd5de34cb820e/skbio/diversity/alpha/_base.py#L1073

**Comment by wasade** [comment]
Thanks, @colinvwood. Do you have a recommended replacement reference by chance?

**Comment by colinvwood** [comment]
I don't unfortunately, I was trying to learn more about the metric myself.

**Comment by mortonjt** [comment]
You are probably looking for Simpson, E. H. 1949. “Measurement of
Diversity.” Nature 163 (4148): 688–688. <http://paperpile.com/b/LEIA8B/A4bs>
https://www.nature.com/articles/163688a0

**Comment by mataton** [comment]
Is this the correct reference? I'll do a quick PR to fix if it is. I'm not sure if Simpson evenness is mentioned in this paper, though this is not my area of expertise.

**Comment by mortonjt** [comment]
For *evenness*, no that is not the correct reference.  This is
https://www.sciencedirect.com/science/article/abs/pii/0022519366900130?via%3Dihub

**Comment by qiyunzhu** [comment]
@mortonjt Matt and I did some literature review. We found that the original article about "Simpleson's evenness" is vague, and the most operationally appropriate citation would be "Simpson, E. H. (1949). Measurement of diversity. Nature, 163(4148), 688-688." (i.e., the same as `simpson`'s).

**Comment by mortonjt** [comment]
Hi yes I agree, youd need to cite both

**Comment by mataton** [comment]
Fixed with PR #1931.
