### ISSUE TITLE
Ignore Cython-derived .c files

### ISSUE THREAD

**Issue by qiyunzhu** [scikit-bio/scikit-bio#1950]
At present, multiple .c files are included in the skbio repo. These files were generated during the installation process (`pip install`), and they change every time one installs skbio. Therefore, a developer has to do `git restore **.c` when they set up a new development environment. This behavior is not documented in the contributor's guidelines.

I would suggest that we exclude those files from the skbio repo. They are not for human reading, and they will be (re)generated during installation anyway.

At present, there are only six such files: `_phylogenetic.c`, `_ssw_wrapper.c`, `__subsample.c`, `_cutils.c`, `_cutils.c`, `_intersection.c`. Additionally, there is `ssw.c`, which is part of the repo (but we will remove it soon once we drop SSW at all). Therefore, to exclude the six .c files, we can add two lines: `*.c` and `!ssw.c` to `.gitignore`.

Is my understanding accurate? What do you think of this proposal? @wasade @mortonjt

**Comment by mataton** [comment]
Resolved with PR #1958.
