### ISSUE TITLE
Add coverage to CI?

### ISSUE THREAD

**Issue by qiyunzhu** [scikit-bio/scikit-bio#1951]
The scikit-bio repo once had coverage as part of CI, and the coverage % is reported in a badge, powered by the code analysis service [coveralls](https://coveralls.io/). However, the badge is not working any more. I would suggest that we update this. Meanwhile, I would suggest that we consider switching from coveralls to [codecov](https://about.codecov.io/). Many other open-source projects use this service. Some examples are scikit-learn, conda, matplotlib, and statsmodels. Currently, scikit-bio has an overall coverage of 99%, which is higher than many big names. This is something we can pride on and maintain. What do you think? @wasade @mortonjt @mataton

**Comment by mataton** [comment]
@qiyunzhu I like this idea. I can add this to my list of items to work on, if we all want to make this switch.

**Comment by qiyunzhu** [comment]
@mataton I can give it a try to see if there is a quick solution. I had experience with coveralls in the past.

**Comment by qiyunzhu** [comment]
With Matt's help we now have a coverage badge! Powered by Codecov.io. @mortonjt @wasade 

![image](https://github.com/scikit-bio/scikit-bio/assets/4396343/4901939f-7a55-4863-a6a5-a8a5d653e30b)
