### ISSUE TITLE
Top-level module `feature_table` should be added to documentation

### ISSUE THREAD

**Issue by qiyunzhu** [scikit-bio/scikit-bio#1991]
It doesn't show in the documentation (https://scikit.bio/docs/dev/index.html). The solution is to add a file [like this](https://github.com/scikit-bio/scikit-bio/blob/main/doc/source/metadata.rst) @wasade I can do it easily, but I wanted to check with you first in case you have more plans on the documentation.

**Comment by qiyunzhu** [comment]
Update: I addressed this in #1992 . Although the documentation still needs to be enriched.

**Comment by wasade** [comment]
Thanks!
