### ISSUE TITLE
hdmedians is not available from conda-forge for windows

### ISSUE THREAD

**Issue by mataton** [scikit-bio/scikit-bio#1996]
[hdmedians](https://github.com/daleroberts/hdmedians) is unavailable from conda-forge on windows. Adding windows support is a goal of scikit-bio over the next year. Currently hdmedians is only used in a single function in skbio:  `_permdisp._config_med()`. 

We may consider implementing hdmedians within skbio, as hdmedians has the Apache 2.0 license which may be compatible with our own license. Alternatively we may consider replacing hdmedians with another package which is available on conda-forge for windows and more actively maintained.

@qiyunzhu had this idea initially. @wasade and @mortonjt what are your thoughts?

**Comment by mortonjt** [comment]
Looking at the source code, it actually looks pretty minimal. The only
possible concern is porting the extra cython code from hdmedians - we’d
need to make sure that the cython code also ports to windows

**Comment by qiyunzhu** [comment]
@mataton This is great to know! Thanks! Yes let's port hdmedians.

The relevant hdmedians function is [`geomedian`](https://github.com/daleroberts/hdmedians/blob/19113b0a3496fed45bdf75740ff47f35bd420271/hdmedians/geomedian.pyx#L393C1-L393C16), which in turn calls [`geomedian_axis_one`](https://github.com/daleroberts/hdmedians/blob/19113b0a3496fed45bdf75740ff47f35bd420271/hdmedians/geomedian.pyx#L150). I think that `geomedian_axis_one` is the only function we need to port (along with any utility functions it calls, like `dist_euclidean` and `norm_euclidean`).

**Comment by mataton** [comment]
Looks good, would `stats/distance/_utils.py` be a good place to put these?

**Comment by mataton** [comment]
Closed with PR #2003.
