### ISSUE TITLE
Protein LLM data structures

### ISSUE THREAD

**Issue by mortonjt** [scikit-bio/scikit-bio#2006]
After some thought / discussion, it may be best to define a few data structures, one to wrap the output of typical pLMs (i.e. ESM2, Protrans, ...), and data structures that wraps the protein vectors generated by tools such as TMvec, Proteinvec, ...

The main utility of these containers is to have standard data structures / file formats to standardize these workflows via `save` and `load` functions. There can be additional functionality added later (i.e. filter, query, classify, to_ordination, to_anndata, ...)

To get started, we can consider the following classes

```python
class ProteinEmbedding(Protein):
    def __init__(self, embedding : np.array], sequence : skbio.Sequence, source_model : str = None)
         self.embedding = embedding
         self.sequence = sequence
        
    def save(self, filename): # to be implemented in the io registry
         ...
    def load(self, filename, mode='w'):
         ...

class ProteinVector(Protein):
    def __init__(self, vector : np.array, sequence : skbio.Sequence, source_model : str = None):
         self.vector = vector
         self.sequence = sequence
    def save(self, filename): # to be implemented in the io registry
         ...
    def load(self, filename, mode='w'):
         ...

class TabularProteinVectors():
    def __init__(self, vectors : ProteinVector):
         self.vectors = vectors  # and more processing to follow

    def save(self, filename): # to be implemented in the io registry
         ...
    def load(self, filename, mode='w'):
         ...
```
This structure is chosen to match the existing skbio organization (i.e. Sequence vs TabularMSA).
For ProteinEmbeddings, a tabular format doesn't necessarily make sense, since the proteins will all be of different lengths.  Also each protein will likely be analyzed independently (i.e. alignment). In contrast, ProteinVectors will all have the same length if generated from the same model. Hence keeping track of which model generated the embeddings / vectors becomes crucial due to compatibility (i.e. `source_model`).

The other consideration is that I/O will become an issue if all of the sequences need to be loaded into memory prior to saving to disk. Thus, being able to append objects to memory in a stream fashion will become a strong advantage of these data structures. See here for an example of how to do this : https://github.com/tymor22/tm-vec/pull/22

Action items
- [ ] Implement Protein subclasses
- [ ] Implement read / write to HDF5 format
- [ ] Make sure that repr and other functions still work

TODO later
- [ ] Interface to DuckDB / pgvector / faiss
- [ ] Conversion to OrdinationResults
- [ ] Conversion to AnnData

**Comment by wasade** [comment]
Thanks @mortonjt, this is super cool. With the object model, would it make sense to include classes for `DNA` and `RNA` as well?

**Comment by mortonjt** [comment]
Eventually yes, but we would need a path forward to identify DNA and RNA pretrained LLMs that can deal with these types.  For DNA, there are a number of different use cases, whether it be working with short contigs via [DNABert](https://github.com/jerryji1993/DNABERT), or whole genomes like [Evo](https://arcinstitute.org/news/blog/evo).  There are also a number of other RNA foundation models (i.e. [CodonBert](https://www.biorxiv.org/content/10.1101/2023.09.09.556981v1.full.pdf)).

The issue is that I'm not familiar with these models, and thus, we would need to carefully define the requirements (i.e. the corresponding models and downstream applications) -- this is quite non-trivial.  For the protein language models, this is relatively straightforward, since we have DeepBLAST, TMvec, ESM2 / Protrans as our initial models -- it'll be easier to onboard additional pLMs.

**Comment by wasade** [comment]
Fair. Would it make sense to at least stub out the objects and have them raise `NotImplementedError` appropriately to get the namespace organized in anticipation of future development?

**Comment by mortonjt** [comment]
Maybe - the issue is that the downstream could have wildly different applications. Storing embeddings for an entire genome would have very different implications compared to working with contigs, plasmid or viral genomes (its not even clear to me if this would make sense). It currently isn't clear to me what a high-level ecosystem would look like outside of these stubs.

Right now, I'm planning on having both `ProteinEmbedding` and `ProteinVector` both inherent from the `Protein` class.  Below is the current sketch of the `ProteinEmbedding` class (that pull request will go in first once the tests are in). In essence, this `ProteinEmbedding` object will be a `Protein` subclass that contains additional metadata, which include the `embedding` data structure.  

Most of the heavy lifting in this pull request will be through defining the HDF5 format, which will help with shuttling around these embeddings.

```python
class ProteinEmbedding(Protein):
    """Stores the embeddings of the protein sequence.

    Parameters
    ----------
    sequence : str, Sequence, or 1D np.ndarray (np.uint8 or '\|S1')
        Characters representing the protein sequence itself.
    embedding : np.ndarray
        The embedding of the protein sequence. Row vectors correspond to
        the latent residues coordinates.
    metadata : dict, optional
        Arbitrary metadata which applies to the entire sequence.
    positional_metadata : Pandas DataFrame consumable, optional
        Arbitrary per-character metadata. For example, quality data from
        sequencing reads. Must be able to be passed directly to the Pandas
        DataFrame constructor.
    interval_metadata : IntervalMetadata
        Arbitrary interval metadata which applies to intervals within
        a sequence to store interval features (such as protein domains).
    lowercase : bool or str, optional
        If ``True``, lowercase sequence characters will be converted to
        uppercase characters in order to be valid IUPAC Protein characters. If
        ``False``, no characters will be converted. If a str, it will be
        treated as a key into the positional metadata of the object. All
        lowercase characters will be converted to uppercase, and a ``True``
        value will be stored in a boolean array in the positional metadata
        under the key.
    pad_start : bool, optional
       If ``True``, the start of the sequence will be padded with a gap
       character. If ``False``, the start of the sequence will not be padded.
       Some language models specify start tokens, and this parameter can
       be used to account for this.
    pad_end : bool, optional
       If ``True``, the end of the sequence will be padded with a gap
       character. If ``False``, the end of the sequence will not be padded.
       Some language models specify end tokens, and this parameter can
       be used to account for this.
    validate : bool, optional
        If ``True``, validation will be performed to ensure that all sequence
        characters are in the IUPAC protein character set. If ``False``,
        validation will not be performed. Turning off validation will improve
        runtime performance. If invalid characters are present, however, there
        is **no guarantee that operations performed on the resulting object
        will work or behave as expected.** Only turn off validation if you are
        certain that the sequence characters are valid. To store sequence data
        that is not IUPAC-compliant, use ``Sequence``.

    See Also
    --------
    Protein
    """

    def __init__(
        self,
        sequence,
        embedding,
        metadata=None,
        positional_metadata=None,
        interval_metadata=None,
        lowercase=False,
        pad_start=False,
        pad_end=False,
        validate=True,
    ):
        super(ProteinEmbedding, self).__init__(
            sequence, metadata, positional_metadata, interval_metadata, lowercase
        )
        # make sure that the embedding has the same length as the sequence
        sequence_len = len(sequence) + int(pad_start) + int(pad_end)
        if len(embedding) != sequence_len:
            raise ValueError("The embedding must have the same length as the sequence.")
        self.embedding = embedding
```

**Comment by mortonjt** [comment]
I see where you are coming from -- and I currently do not see a use case
where only the embedding information is needed, not the sequence, since the
sequence itself is an identifier). If we can avoid adding too many ABCs, we
should sense it would add additional complexity and make it more difficult
to understand the underlying codebase.

That being said, we discussed the possibility of generating an
`OrdinationResults` object from a `ProteinEmbedding` /
`TabularProteinVectors`object (which will also need the sequence
information to label the coordinates). The only crux that may be worth
highlighting is the potential for a `ProteinStructure` class that may end
up inheriting from a `ProteinEmbedding` class, which that contains the 3D
coordinates for each residue, as well as interaction information (i.e.
disulfide bridges) and other attributes (i.e. post-translational
modifications).  But it isn't exactly clear how this information should be
structured, so let's defer this thought process

**Comment by qiyunzhu** [comment]
There are certainly uses cases for non-protein sequences. For example, the RNA secondary structure is directly related to how 16S primers were designed. In a genome annotation task, proteins are the most important, but there are rRNAs, tRNAs, ncRNAs, CRIPSRs, transposons etc. which are also important. So I hope that the data structure to be implemented is not too specific to a single sequence type. That will make future expansion difficult.

For the current design (see below), I am concerned that fundamental data structures like embedding and structure is burried too deep in the hierarchy. 

`Sequence` > `GrammaredSequence` > `Protein` > `ProteinEmbedding` > `ProteinStructure`

How about having embedding and structure as top-level classes, then have protein, DNA and RNA as subclasses of them. I guess that alphabet is the only fundamental thing that differentiate them. Currently there is no `Alphabet` class, but the recently implemented `SubstitutionMatrix` class has some code that can be elevated into a separate `Alphabet` class.

**Comment by qiyunzhu** [comment]
On another thought, would it be useful / practical to have a sequence type-agnostic `Embedding` class? An embedding object can be assigned to a sequence object as an attribute. That will save the trouble of future restructuring or duplicating code.

**Comment by mortonjt** [comment]
> There are certainly uses cases for non-protein sequences.

We're not disputing that, it's primarily a matter of enforcing a structure to enable this down the road. But I think I see your point -- rather than implementing embedding subclasses for each single type which would be essentially copying the embedding attributes / functions multiple times), rather create an embedding ABC that itself can be subclassed out to enforce the API structure.

So this new structure would be  `SequenceEmbedding` > `ProteinEmbedding`, and have `ProteinEmbedding` also take in as input the `Protein` sequence as an object in the constructor (in addition to the embedding).  That way, the sole purpose of the `Protein` object is to act like an identifier.

I think having structure objects as separate entities also makes sense, so let's revisit once the embedding objects are done.

**Comment by mortonjt** [comment]
I'm also OK with having a separate embedding object -- this could become very useful for molecular / mass spectrometry data types.

**Comment by mortonjt** [comment]
I'm beginning to flesh out the io format, I'm seriously considering loading an entire fasta file into hdf5, it would look something as follows
```python
def _object_to_embed(obj, fh, mode='w'):
    emb = obj.embedding
    emb = emb.reshape(1, emb.shape[0], emb.shape[1])
    # store fasta representation of sequence
    with StringIO() as f2:
        _sequence_to_fasta(obj, f2)
        seq_repr = f2.getvalue()
    arr = np.array([ord(s) for s in list(seq_repr)])
    
    h5grp = h5py.File(fh, mode)
    
    if "embedding" in h5grp:
        seq_embed = h5grp["embedding"]
        n = seq_emb.shape[0]
        seq_embed.resize(n, axis=0)
        seq_embed[-1] = emb
    else:
        seq_embed = h5grp.create_dataset("embedding", data=emb,
                                          maxshape=(None, emb.shape[1], emb.shape[2]),
                                          dtype=emb.dtype)
    
    if "fasta" in h5grp:
        seq = h5grp["fasta"]
        m = len(seq)
        seq.resize(m + len(arr))
        seq[m : m + len(arr)] = arr
    else:
        seq = h5grp.create_dataset("fasta", data=arr,
                                   maxshape=(None,),
                                   dtype=np.int32)

    if "faidx" in h5grp:
        faidx = h5grp["faidx"]
        n = seq_embed.shape[0]     
        seq = h5grp["fasta"]
        faidx.resize(n)
        seq[n] = len(arr)
    else:
        seq = h5grp.create_dataset("faidx", data=[len(arr)],
                                   maxshape=(None,),
                                   dtype=np.int32)
```

Benefits of having the entire fasta format coupled with the sequence embedding file
1. It would link the sequence and embedding objects, so that the identifiers won't be disconnected. This would help with book keeping
2. We can recycle the existing fasta io formatting in skbio. This would provide another mechanism for encoding metadata into these objects
3. Because we are recycling the fasta io, there is lower maintenance burden

Disadvantages of using the fasta format
1. It does as some additional complexity. To build generators, we would need to keep track of the boundaries of the fasta sequence representations (aka the faidx object).
2. It may appear complicated to external developers, since they would have to parse out a byte representation of fasta files from the hdf5 file in order to extract the sequence / metadata information. 

The other solution would be to forget about the fasta format, and directly encode byte strings for the sequences, and encode the corresponding sequence ids (if they exist). We would still need to keep track of the boundaries since we would need to store all of the strings into a single 1D array, but it would look more like a sparse array format (without the additional complexity induced by fasta). The metadata concerns here would still be outstanding though -- but perhaps adding a table to hdf5 is good enough?

**Comment by wasade** [comment]
This is becoming quite an interesting thread! 

@mortonjt, hdf5 does not support jagged arrays so there will be loss but which can be dampened by using compression (e.g. gzip) which is supported natively. We did a lot of [work](https://github.com/qiita-spots/qiita-files/blob/master/qiita_files/demux.py) years ago in a similar area which may be a base to build from. That said, one alternative that you may want to look at, if not done already, is DuckDB + parquet for embeddings or sqlite + sqlite-vss, and `samtools faidx` for indexing sequences. The collection of files could then be placed in a portable container type like zip, and a minor abstraction on top could assert benefit (1). With (2)/(3), we may want to generally consider `samtools faidx` support which likely can be done w/o a dependency as to avoid in-memory representations of large sequence collections.

**Comment by mortonjt** [comment]
Added intefaces to DuckDB / pgvector / faiss to action items above since that is a good idea. And thanks for the link, I'll look over how fasta is embedded there. The other caveat to consider to using the fasta format is that this is specific to sequential data. If we have molecular embeddings for instance, this doesn't make much sense to cram SMILES strings into a fasta format. So in this respect, the second option may be preferable to have a universal embedding format to handle sequences, molecules and potentially other representations.

Regarding hdf5 jagged arrays, yes that makes sense, hence the need for keeping track of boundaries. Correct `samtools faidx` has support for this, but it is quite simple to port, I have code that replicates the faidx functionality if necessary. My major concern is making a design decision now that creates inconveniences down the road (i.e. creating an unique embedding format for each biological representation).

Regarding your comment on "collection of files", are you proposing to do something similar to what the qiime2 Artifacts proposed? I.E. have multiple disjoint files (i.e. embedding file, metadata file, fasta file) that are then zipped together? That would definitely simplify some of these design -- then then only requirement here is to make sure that the primary keys are contained within the embedding file to ensure that the linking can be done. Since sequences (nor molecules for that matter) are guaranteed to have additional ids, it probably makes sense to still embed these string representations in the hdf5 file (but maybe we don't need to worry about metadata for instance).

**Comment by wasade** [comment]
pgvector would not be an embedded process, and would depend on a server right?

w/ collection of files, yes although not necessarily .zip or an q2-artifact like format. It's not unusual to bundle a collection of related files together in a single entity, particularly as one format may be well fit for a particular type of data but not great for other data. If looked at as a collection, then the representation of the sequence or molecular data could be deferred to a subtype that is specific to the data instead of coercing fasta

**Comment by mortonjt** [comment]
Correct, molecular representations should be handled in a different subclass

After some thought, I think we can ditch the idea of a `TabularProteinVector` class. We can instead migrate all of its functionality into the `ProteinVector` class.  It could looks something as follows. We can have the `ProteinVector` class have its own dataframe, ordination and distance_matrix class methods. This would enable the ProteinVector class to more seamlessly integrate into the rest of the skbio ecosystem

```python
class ProteinVector(SequenceVector):
    """ A vector representation of the protein sequence.

    Parameters
    ----------
    sequence : str, Sequence, or 1D np.ndarray
        Characters representing the protein sequence itself.
    vector : np.ndarray
        The vector representation of the protein sequence.

    See Also
    --------
    Protein

    """

    def __init__(
        self, vector, sequence: str, **kwargs
    ):
        super(ProteinVector, self).__init__(
            embedding=vector, sequence=sequence,  **kwargs
        )

    def __str__(self):
        return str(self._ids)

    def __repr__(self):
        """
        Return a string representation of the ProteinVector object.

        Returns
        -------
        str
            A string representation of the ProteinEmbedding object.

        See Also
        --------
        Protein
        """
        seq = Protein(str(self._ids))

        rstr = repr(seq)
        rstr = rstr.replace("Protein", "ProteinVector")
        n_indent = 4  # see Sequence.__repr__
        indent = " " * n_indent
        rstr = rstr.replace(
            "has gaps",
            f"vector dimension: {self.embedding.shape[1]}\n{indent}has gaps",
        )
        return rstr

    @staticmethod
    def to_distance_matrix(protein_vectors):
        """
        Convert a ProteinVector object to a DistanceMatrix object.

        Parameters
        ----------
        protein_vectors : iterable of ProteinVector objects
            An iterable of ProteinVector objects.

        Returns
        -------
        DistanceMatrix
            A DistanceMatrix object.

        See Also
        --------
        DistanceMatrix
        """
        pass

    @staticmethod
    def to_ordination(protein_vectors):
        """
        Convert a list of ProteinVector objects to an Ordination object.

        Parameters
        ----------
        protein_vectors : iterable of ProteinVector objects
            An iterable of ProteinVector objects.

        Returns
        -------
        Ordination
            An Ordination object.

        See Also
        --------
        Ordination
        """
        pass

    @staticmethod
    def to_dataframe(protein_vectors):
        """
        Convert a list of ProteinVector objects to a pandas DataFrame.

        Parameters
        ----------
        protein_vectors : iterable of ProteinVector objects
            An iterable of ProteinVector objects.

        Returns
        -------
        DataFrame
            A pandas DataFrame.

        See Also
        --------
        DataFrame
        """
        pass

```

**Comment by valentynbez** [comment]
> After some thought, I think we can ditch the idea of a `TabularProteinVector` class. We can instead migrate all of its functionality into the `ProteinVector` class. It could looks something as follows. We can have the `ProteinVector` class have its own dataframe, ordination and distance_matrix class methods. This would enable the ProteinVector class to more seamlessly integrate into the rest of the skbio ecosystem. 

I think there should be something similar for `TabularProteinVecor`, with a different name. It is an important strategic concept. 
We need to decouple two different abstractions: 
## **Per residue embeddings** 
Examples: `ProtT5`  

They will have a shape $L \times N_{dim}$, where:
- $L$ is the length of the protein. It is an inconsistent dimension. 
- $N_{dim}$ is the number of dimensions in the model. It is a consistent dimension across a single model.  
This is covered by `ProteinVector`. To me, it's unclear what ordination or distance matrices can be calculated on them, I don't think they're needed yet.

## Per sequence embeddings 
Examples: `TM-Vec`, averaged `ProtT5`, `DeepFRI` [last layer](https://www.nature.com/articles/s41467-023-37896-w) or the craziest - [embedding from Llama](https://arxiv.org/abs/2402.16445))

They will be 1D vectors of shape $N_{dim}, that is defined by the number of dimensions in the model. They will allow to building of consistent dimensions for the whole dataset of proteins- here `OrdinationResult` and `DistanceMatrix` can be applied for downstream analysis, because distances can only be calculated on 1D vectors. Here we need to define `EmbeddingsMatrix` class or smth, on which transformations to `scikit-bio` objects can be applied.


P.S. 3D Ordination visualization is very cumbersome and becomes cluttered quickly, IMHO it should be removed from the package. Unless it's an interactive `plotly` style, 3D should be avoided, and loading figures automatically should be avoided as well.

**Comment by mortonjt** [comment]
Hi @valentynbez for your comment, and I want to continue this conversation to identify usecases for `EmbeddingMatrix` that would be missed from instead defining a `ProteinVector.to_dataframe(vectors : Iterable[ProteinVector]) -> pd.DataFrame`. Do you envision the `EmbeddingMatrix` to have additional functionality outside of passing data to sklearn?

**Comment by valentynbez** [comment]
I think it more appropriate to calculate distance between vectors on `EmbeddingMatrix` and apply different dimensionality reduction on it, which should lead to `OrdinationResults`. It will be more efficiently glued via class.

**Comment by mortonjt** [comment]
Hi, after some thought, we have decided to push forward with the proposed `ProteinVector` design.  The primary interface here would be to facilitate conversions between `List[ProteinVector]` objects to `pd.DataFrame`, `OrdinationResults`, `DistanceMatrix` and `np.array` objects. This is to avoid additional maintenance (and user) burden of dealing with too many objects, while avoiding redundancy of operations wrt to existing objects in numpy / pandas / skbio. We will revisit the `EmbeddingMatrix` class in the future if there is a pressing need for such a class.
