### ISSUE TITLE
Remove last few cases of `np.random`

### ISSUE THREAD

**Issue by qiyunzhu** [scikit-bio/scikit-bio#2096]
NumPy's new random number generator (`rng`) needs to be adopted to replace all cases of old `np.random`. Here is an explanation (#1886). Here is an [example](https://scikit.bio/docs/latest/generated/skbio.stats.composition.dirmult_ttest.html) (see how `seed` is treated).

**Comment by mataton** [comment]
Note: cases under `skbio.tree.TreeNode` can be skipped.

**Comment by qiyunzhu** [comment]
Closing as it has been resolved.
