### ISSUE TITLE
skbio.write index out-of-range error for embeddings

### ISSUE THREAD

**Issue by paarth-b** [scikit-bio/scikit-bio#2097]
## Description

**While developing the scikit-bio-tutorials repo, I ran into the following attached issue:**
![image](https://github.com/user-attachments/assets/d1dbd11f-f618-44c5-8a6b-4e536ac7665d)

When attempting to write embedding objects to a new file, the `_objects_to_embed` method runs into a resize issue.

### Steps to Reproduce

1. Import necessary modules in `\scikit-bio-tutorials/02-language-model/language_model_tutorial.ipynb`
2. Run helper_functions for step 1.
3. Run step 1 code block, then add code:
```
from skbio.io import write

write(embed_list, format='embed', into='data/pdb_hits.h5')
```

### Expected Behavior

Print out all embeddings in skbio format.

## Current Context

After testing, I believe the issue could stem from the resizing logic in the `_objects_to_embed` function, as the error occurs when a resize doesn't increase the `idptr_fh` array size to be greater than `i`. Still in progress, will update after more debugging.

## Screenshots/Logs

Error Message:
![image](https://github.com/user-attachments/assets/ec164518-3cd9-4a90-a9d8-07509eaa68a5)

Print Statement Outputs:
![image](https://github.com/user-attachments/assets/98c139d9-40eb-453a-a636-57d916282dc0)

**Comment by qiyunzhu** [comment]
@paarth-b This is a very well written issue! :+1: :+1:

**Comment by paarth-b** [comment]
![image](https://github.com/user-attachments/assets/fde32d07-bb1b-4e78-9719-f09ffbc4e811)

After some testing, It's pretty clear the issue stems from the idptr_resize not functioning as intended. By removing the if condition in resizing, I was able to execute the testcases. I'll be linking my testing branch shortly.

The downside to this change is not efficiently resizing the id and embedding pointers. Will discuss this with @mortonjt in the meeting tomorrow.

**Comment by paarth-b** [comment]
[error_testing_2097 branch](https://github.com/paarth-b/scikit-bio/tree/error_testing_2097)

**Comment by paarth-b** [comment]
### Resolved 🎉 

Updated PR with bugfix. #2100
