### ISSUE TITLE
Duplicate observation IDs error even no duplication was found

### ISSUE THREAD

**Issue by quliping** [scikit-bio/scikit-bio#2121]
Hello, I tried to transfer dataframe to a biom Table using the skbio.table.Table. However, I got 'biom.exception.TableException: Duplicate observation IDs' error even I already removed potential duplicate ids using pandas. I also checked species ids and sample ids using Excel, no duplication was found. Is there any wrong in my scripts? Thanks.

![1](https://github.com/user-attachments/assets/9c2fc148-ca04-46f4-b8c6-0ba9fef1f7c7)
![2](https://github.com/user-attachments/assets/2d6bdda4-2bcb-43ee-814c-4bef606e8c48)
[archaea_bundance_df.txt](https://github.com/user-attachments/files/16828270/archaea_bundance_df.txt)

**Comment by mortonjt** [comment]
Hi, this looks like a biom exception, let's move this issue over.

I'd try running the `set(observation_ids)` to make sure that the size of the set isn't smaller than `observation_ids`

**Comment by quliping** [comment]
This problem was solved by https://github.com/biocore/biom-format/issues/976, and I closed this question.
