### ISSUE TITLE
Error when using the `skbio.diversity.beta_diversity`

### ISSUE THREAD

**Issue by quliping** [scikit-bio/scikit-bio#2125]
Hello, recently, I tried calculating beta diversity using the `skbio.diversity.beta_diversity`. First, I hvae confirmed that the version of SciPy and scikit-bio is 1.14.1 and 0.6.2, repectively. Second, for the input table of `skbio.diversity.beta_diversity`,  each column is a species/OTU and each row is a sample, right? But I got some problems: 

1. 'jensenshannon' and 'kulczynski1' got a 'Metric XXX is not available' error, even I found the scipy indeed suport these two metrics, and I indeed used the latese version of skbio and scipy.
![image](https://github.com/user-attachments/assets/15729102-b523-4405-92f3-4bc756d5cc9e)
![image](https://github.com/user-attachments/assets/d89ab645-003d-48df-a26b-c348de4b040b)

2. This problem occurred only when calculating the 'mahalanobis' metric. One of `skbio.diversity.beta_diversity` and `scipy` seems to have a mistake in the row and column contents? Because If I use `rarefy_df, ids=observation_ids` or just use ` rarefy_df` (lines 157 - 159 in my script), no error was given. `rarefy_df` is the input table. 
![image](https://github.com/user-attachments/assets/d92b26e9-68fc-43a7-af95-658878cb1f8e)

Here is a part of my script:
![image](https://github.com/user-attachments/assets/0c03a0e6-cb89-466b-85cd-22a3b09320f3)

Here is my input table, each row/index is a species (n = 193) and each column is a sample (n = 76):
[archaea_bundance_df.txt](https://github.com/user-attachments/files/16916711/archaea_bundance_df.txt)

Here is the software version, I print it using `skbio.__version__` and `scipy.__version__`:
![image](https://github.com/user-attachments/assets/de2441d8-0c24-457d-8a94-56362cc358b5)
![image](https://github.com/user-attachments/assets/0a6e151f-25d9-4903-9bbc-a2a4d54baf08)

By the way, I don't know why the results of some metrics contains negative eigenvalues. Is it caused by the input data? Because I used the normalization abundance (RPKM/TPM) of my MAGs from a metagenomic data rather than tranditional integer format abundance of OTUs from the 16S high throughput sequencing. I will try some tranditional data in the next few days to see if the problem will still occur.
![image](https://github.com/user-attachments/assets/06a9c3a3-eda0-4420-b71b-11ebb9270c68)

**Comment by qiyunzhu** [comment]
Hi @quliping Thanks for reporting this. scikit-bio has a list of available beta diversity metrics built-in, which can be listed by [`skbio.diversity.get_beta_diversity_metrics`](https://scikit.bio/docs/latest/generated/skbio.diversity.get_beta_diversity_metrics.html). Most of these metrics correspond to metrics supported by [`scipy.spatial.distance.
pdist`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html). However, not all metrics supported by the latter were included in the former. Here is a [list of them](https://github.com/scikit-bio/scikit-bio/blob/7faf971d3af70d2decb8fbe44660ceaf8883641e/skbio/diversity/_driver.py#L330). It could be that the original developer of the beta diversity function reviewed `pdist` metrics and selected a subset of valid beta diversity metrics. It could also be that when the beta diversity function was originally implemented, `pdist` didn't have the missing metrics yet.

For the negative eigenvalue issue let me ping @wasade

**Comment by quliping** [comment]
> 2\. mahalanobis
@qiyunzhu Thanks for your kindly reply. I foud that the `beta_diversity()` function in the `_driver.py` calculates sample distances using scipy.spatial.distance.pdist and return a DistanceMatrix. Therefore, I think adding metrics supported by scipy but not supported by skbio to the `_valid_beta_metrics` in the `_driver.py` by myself is a feasible way to solve the first problem. 

For the error of 'mahalanobis' calculation described in question 2, I found it is not the problem of skbio but is the issue of scipy. Since I test the calculation using `scipy.spatial.distance.pdist(df)` and got the same error. 
The test dataframe `df` have sample ids (n = 76, e.g., SY11_733_S_0-2) in rows and species ids (n = 193, e.g., bin.SY38.6_arc_sp.1_1) in columns. Scipy throw the error when input is `df` but no error when input is` df.T`. Seems that scipy requires a table with more rows ('observations' in scipy and 'samples' in skbio) than columns ('dimensionality' in scipy and 'OTUs' in skbio) when calculating the 'mahalanobis' metirc. I searched for some information about the 'mahalanobis distance', and found that it indeed needs a number of samples lager than the dimensionality number. However, it is very terrible for deversity analysis, because we always have a large number of OTUs/species (that is, dimensionality) with a relatively small number of samples. In other words, we always have a table with more columns than rows. Maybe the mahalanobis metric need to be removed from scikit-bio.
![image](https://github.com/user-attachments/assets/4cf6c12e-fe0c-4490-aafd-51a05704bda8)

Still waiting for the discussion of the negative eigenvalue issue.

**Comment by quliping** [comment]
> Hi @quliping Thanks for reporting this. scikit-bio has a list of available beta diversity metrics built-in, which can be listed by [`skbio.diversity.get_beta_diversity_metrics`](https://scikit.bio/docs/latest/generated/skbio.diversity.get_beta_diversity_metrics.html). Most of these metrics correspond to metrics supported by [`scipy.spatial.distance. pdist`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html). However, not all metrics supported by the latter were included in the former. Here is a [list of them](https://github.com/scikit-bio/scikit-bio/blob/7faf971d3af70d2decb8fbe44660ceaf8883641e/skbio/diversity/_driver.py#L330). It could be that the original developer of the beta diversity function reviewed `pdist` metrics and selected a subset of valid beta diversity metrics. It could also be that when the beta diversity function was originally implemented, `pdist` didn't have the missing metrics yet.
> 
> For the negative eigenvalue issue let me ping @wasade

Hi @qiyunzhu , thanks for your kindly reply. I foud that the `beta_diversity()` function in the `_driver.py` calculates sample distances using scipy.spatial.distance.pdist and return a DistanceMatrix. Therefore, I think adding metrics supported by scipy but not supported by skbio to the `_valid_beta_metrics` in the `_driver.py` by myself is a feasible way to solve the first problem. 

For the error of 'mahalanobis' calculation described in question 2, I found it is not the problem of skbio but is the issue of scipy. Since I test the calculation using `scipy.spatial.distance.pdist(df)` and got the same error. 
The test dataframe `df` have sample ids (n = 76, e.g., SY11_733_S_0-2) in rows and species ids (n = 193, e.g., bin.SY38.6_arc_sp.1_1) in columns. Scipy throw the error when input is `df` but no error when input is` df.T`. Seems that scipy requires a table with more rows ('observations' in scipy and 'samples' in skbio) than columns ('dimensionality' in scipy and 'OTUs' in skbio) when calculating the 'mahalanobis' metirc. I searched for some information about the 'mahalanobis distance', and found that it indeed needs a number of samples lager than the dimensionality number. However, it is very terrible for deversity analysis, because we always have a large number of OTUs/species (that is, dimensionality) with a relatively small number of samples. In other words, we always have a table with more columns than rows. Maybe the mahalanobis metric need to be removed from scikit-bio.
![image](https://github.com/user-attachments/assets/4cf6c12e-fe0c-4490-aafd-51a05704bda8)

Still waiting for the discussion of the negative eigenvalue issue.

**Comment by qiyunzhu** [comment]
@quliping Thank you for doing the research and letting us know your findings.

Given your finding that `mahalanobis` requires more samples than features, which is rarely the case in omic data analysis, I am prone to remove `mahalanobis` from scikit-bio.

For `jensenshannon`, it seems to be a valid beta diversity metric. There is a previous issue #1541 for this. I would suggest adding this metric to scikit-bio.

For `kulczynski1`, we once decided to excluded it due to backward compatibility issues. See #1887 . But I wonder if you wanted to use this metric for a reason? Say, it is the right metric for your research question?

I will create a PR and ping you and other relevant developers for comments.

**Comment by qiyunzhu** [comment]
@quliping We have taken care of this. Specifically, we 1) added `jensenshannon`, 2) left out `kulczynski1`, 3) still kept `mahalanobis`, but added an error message that is easier to understand than the SciPy one to the user.
